version: '3.8'

services:
  db:
    container_name: posterr_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: posterr
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: posterr_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - ./tmp/postgres-data:/var/lib/pgadmin

volumes:
  postgres-data:
